export const data = {
  name: "Shrabana Goswami",
  tagline: "Frontend Engineer",
  roles: [
    "Frontend Engineer",
    "MERN Stack Developer",
    "Performance Optimizer",
    "UI Architect",
  ],
  email: "shrabanagoswami8@gmail.com",
  phone: "9830564513",
  location: "Kolkata, WB",
  linkedin: "linkedin.com/in/shrabana-goswami-363219236",
  github: "github.com/ShrabanaG",
  summary:
    "4 years crafting responsive, performant web applications. I turn product requirements and design mockups into production-grade UIs with a relentless focus on Core Web Vitals, scalable architecture, and clean code.",
  skills: {
    Frontend: [
      "React.js",
      "Next.js",
      "TypeScript",
      "JavaScript ES6+",
      "Redux Toolkit",
      "Tailwind CSS",
      "Context API",
      "HTML5",
      "CSS3",
      "Jest",
      "React Testing Library",
    ],
    Performance: [
      "Core Web Vitals",
      "Lighthouse",
      "SSR",
      "Code Splitting",
      "Webpack",
      "Vite",
      "WCAG",
      "Lazy Loading",
    ],
    Backend: ["Node.js", "Express.js", "MongoDB", "REST APIs", "JWT", "OAuth2"],
    Cloud: ["AWS S3", "AWS EC2", "AWS IAM", "Vercel", "GitHub"],
    Visualization: ["D3.js", "Chart.js"],
  },
  metrics: [
    {
      label: "Load Time Reduction",
      value: "28%",
      sub: "via SSR & code splitting",
    },
    { label: "LH Performance Score", value: "90+", sub: "all key pages" },
    { label: "Code Coverage", value: "65%+", sub: "Jest & RTL" },
    { label: "Accessibility Score", value: "+85%", sub: "WCAG-first approach" },
  ],
  experience: [
    {
      company: "Gaming Prism Pvt Ltd.",
      role: "Frontend Engineer",
      period: "Feb 2025 – Nov 2025",
      location: "Kolkata, WB",
      color: "#a78bfa",
      bullets: [
        "Championed key features for a social engagement platform — boosted user engagement by 20%",
        "Reduced initial load time by 25–30% via Next.js SSR, middleware routing & code splitting",
        "Built responsive UI across 5+ breakpoints — zero critical layout regressions",
        "Achieved Lighthouse scores above 90 via image optimization & lazy loading",
        "Increased accessibility scores by 85% through WCAG-first code reviews",
      ],
    },
    {
      company: "Advanced Structures India",
      role: "Software Engineer (Contract)",
      period: "Aug 2024 – Oct 2024",
      location: "Remote",
      color: "#34d399",
      bullets: [
        "Built 15+ reusable React components — reduced code duplication by ~30%",
        "Centralized state across 6+ modules using Redux & Context API",
        "Refactored 5+ REST API integrations — improved payload efficiency & load perf",
      ],
    },
    {
      company: "Freelancing",
      role: "Full Stack Developer",
      period: "Dec 2023 – Jul 2024",
      location: "Remote",
      color: "#f59e0b",
      bullets: [
        "Delivered full-stack course management platform (MongoDB, Express, Next.js, Node.js)",
        "Implemented secure auth + RBAC using JWT/OAuth2 — streamlined enrollment by 15%",
        "Responsive UI with Tailwind CSS & Material UI across 5+ device targets",
      ],
    },
    {
      company: "TIF Labs Pvt Ltd",
      role: "Frontend Developer (Contract)",
      period: "Jun 2023 – Aug 2023",
      location: "Bengaluru",
      color: "#60a5fa",
      bullets: [
        "Built React + TypeScript workflow generator UI — 8 configurable steps, cut manual setup by ~3 hrs/workflow",
      ],
    },
    {
      company: "Aeonix Research & Innovations LLP",
      role: "Frontend Engineer",
      period: "Dec 2021 – May 2023",
      location: "Kolkata, WB",
      color: "#f472b6",
      bullets: [
        "Improved UI performance by 40% for data-heavy dashboards via lazy loading & memoization",
        "Owned ~15,000 LOC React/TypeScript frontend codebase",
        "Maintained 65%+ test coverage with Jest & React Testing Library",
        "Mentored 2 junior engineers; shipped 10+ features across 3 teams in agile sprints",
      ],
    },
  ],
  projects: [
    {
      name: "Social Engagement Platform",
      tech: ["React", "Next.js", "Redux", "Tailwind"],
      metrics: ["20% ↑ engagement", "25-30% faster load", "LH 90+"],
      desc: "Full social platform rebuilt as sole frontend engineer — SSR architecture, performance-first from day one.",
      color: "#a78bfa",
    },
    {
      name: "Workflow Generator UI",
      tech: ["React", "TypeScript"],
      metrics: ["~3hr saved/workflow", "8 config steps"],
      desc: "End-to-end process automation tool enabling configurable multi-step workflows for internal teams.",
      color: "#34d399",
    },
    {
      name: "Course Management Platform",
      tech: ["Next.js", "MongoDB", "Express", "Node.js"],
      metrics: ["15% ↑ enrollment", "3 user flows", "4-month delivery"],
      desc: "Full-stack LMS with JWT/OAuth2 auth, RBAC, and responsive UI — delivered solo within scope.",
      color: "#f59e0b",
    },
    {
      name: "Data Dashboard Suite",
      tech: ["React", "TypeScript", "D3.js", "Chart.js"],
      metrics: ["40% faster renders", "15K+ LOC owned"],
      desc: "Heavy data visualization dashboards optimized via memoization and lazy loading for Aeonix's research platform.",
      color: "#60a5fa",
    },
  ],
  education: [
    {
      degree: "B.Tech — Information Technology",
      school: "University of Calcutta",
      year: "2019–2022",
      cgpa: "8.00 CGPA",
    },
    {
      degree: "B.Sc — Computer Science",
      school: "University of Calcutta",
      year: "2015–2019",
      cgpa: "61.75%",
    },
  ],
  certifications: [
    "IITM-Pravartak Full Stack Developer Course",
    "AWS Certified Developer – Associate (Udemy)",
    "Complete AI Guide – ChatGPT & Generative AI (Udemy)",
  ],
};
